standard = "1993"

preferred_case = "lower"

### project code
[libraries.project]
files = ["src/**/*.vhd"]
is_third_party = false

### Quartus megafunctions
[libraries.altera_mf]
files = [
	"/opt/intelFPGA/25.1/quartus/eda/sim_lib/altera_mf.vhd",
	"/opt/intelFPGA/25.1/quartus/eda/sim_lib/altera_mf_components.vhd"
]
is_third_party = true

### hardware drivers
[libraries.hardware]
files = ["src/hardware/**/*.vhd"]
is_third_party = false

### linting rules
[lint]
unused = "error"
# disable linting for the work library
unnecessary_work_library = false
