standard = "1993"

preferred_case = "lower"

### project code
[libraries.project]
files = ["src/**/*.vhd"]
is_third_party = false

[libraries.project_config]
files = ["project_config/**/*.vhd"]
is_third_party = false

### linting rules
[lint]
unused = "error"
# disable linting for the work library
unnecessary_work_library = false